### PR TITLE
Fix issue 8

### PR DESCRIPTION
**Pull request by thiagogabriel**
Makes README better

### CODE REVIEW

**Comment by badosu** [comment]
Thanks a lot dude!

For me it is good to merge!

Wanna close it @rodrigopinto?

**Comment by badosu** [comment]
Hello @thiagogabriel, just noting that your first commit is not related to this pull request, could you remove it?

You can user `git-revert` for this and `git-cherry-pick` it on anotther pull request

Also, please use a different branch than master when you make a pull request. This way we should be able to commit directly in your pull request before merging.

**Comment by badosu** [comment]
Great!! Merging it!

**Comment by thiagogabriel** [comment]
@badosu Sorry. I'll do it on the next. Thanks for the advice.

**Comment by badosu** [comment]
Should not apologize, it is normal dude.

Thanks!

**Pull request merged**
