### PR TITLE
Add avatar placeholder image. Still JPG

### PR DESCRIPTION
**Pull request by thiagogabriel**
Solves https://github.com/playthecall/playthecall/issues/70, but still needs the PNG

### CODE REVIEW

**Comment by marcbzz** [comment]
@thiagogabriel qual seu facebook? precisamos conversar tipo já. :)

**Comment by thiagogabriel** [comment]
@marcbzz é /thiago.gabriel

**Comment by philss** [comment]
I have not tested it, but I think it's ok!
We have the same issue with the sidebar image(left side).

**Comment by badosu** [comment]
For me it's ok! :shipit:

**Comment by eniolopes** [comment]
:+1:

**Comment by eniolopes** [comment]
@thiagogabriel can you rebase this? thanks

**Comment by badosu** [comment]
@eniolopes I don't know if rebasing is practicable right now, could you merge this PR for us?

**Pull request merged**
