### PR TITLE
Embed URL from Youtube

### PR DESCRIPTION
**Pull request by philss**
I forgot a little detail about Youtube URLs:  We need to use the "embed" format to work with iframes.
This issue is related to #95 

The problem:
If we take the default URL from some Youtube video, it will not work because Youtube wants the "embed" URL.
So, when we have: `http://www.youtube.com/watch?v=EigbFw23Urw`, Youtube expects:`http://youtube.com/embed/EigbFw23Urw` to work with iframes

The solution:
I'm using FormattedURL gem to take embed URL for Youtube URLs.

PS.: I'm the author of this gem. Take a look at: https://github.com/philss/formatted_url

### CODE REVIEW

**Comment by badosu** [comment]
Great! Merged

**Comment by badosu** [comment]
Hello @philss, im having problem when installing formatted_url:

```
❯ gem install formatted_url
ERROR:  While executing gem ... (TypeError)
    can't convert Array into String
```

**Comment by badosu** [comment]
Here is a more verbose output:

```
❯ gem install -V formatted_url                                                                                                                                        PlayTheCall/git/master !
GET http://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
GET http://production.s3.rubygems.org/latest_specs.4.8.gz
200 OK
Installing gem formatted_url-0.0.3
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/.gitignore
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/.travis.yml
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/Gemfile
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/Gemfile.lock
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/README.md
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/Rakefile
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/formatted_url.gemspec
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/lib/formatted_url.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/lib/formatted_url/strategies.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/lib/formatted_url/strategies/default_url_strategy.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/lib/formatted_url/strategies/youtube_url_strategy.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/lib/formatted_url/url_source_resolver.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/lib/formatted_url/version.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/test/default_url_strategy_test.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/test/default_url_test.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/test/test_helper.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/test/url_source_resolver_test.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/test/url_strategy_test.rb
/home/badosu/.rvm/gems/ruby-1.9.3-p327/gems/formatted_url-0.0.3/test/youtube_url_strategy_test.rb
ERROR:  While executing gem ... (TypeError)
    can't convert Array into String
```

**Comment by badosu** [comment]
Installed it locally after cloning the repository and it worked. It deployed on heroku, so I think maybe i got a _turbulence_

**Comment by philss** [comment]
Sorry guys!

Hi @badosu , I think it was something with the version number.
I released a new version(0.0.4) that may fix the error(or prevent it to appear again).

I will update Gemfile on master branch, ok?

Thanks!

**Comment by badosu** [comment]
Ok, thank you!

**Pull request merged**
