### PR TITLE
Correct redirect path

### PR DESCRIPTION
**Pull request by thiagogabriel**
#### Existing issues:
1. Besides the fixed redirects_to, it logs out because the user always have to insert a password.
2. The user always have to type a password, accepting the old password or a new one. I think the workflow needs to be changed.

Screen Shot 2012-12-16 at 11 11 16 AM

### CODE REVIEW

**Comment by badosu** [comment]
Hello @thiagogabriel, take a look at this redirection from root path.

https://github.com/playthecall/playthecall/blob/oracle/app/controllers/welcome_controller.rb#L5

**Comment by badosu** [comment]
It redirects to the mission path, but the current one. You can use `redirect_to user_current_mission` instead of `mission_path`

**Comment by badosu** [comment]
@thiagogabriel You can add commits to an already submitted pull request

**Comment by thiagogabriel** [comment]
Now works perfectly if merged with https://github.com/playthecall/playthecall/pull/65

**Comment by badosu** [comment]
Great!

**Pull request merged**
